services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: near-cash-api
    container_name: near-cash-api
    hostname: near-cash-api
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - database
    networks:
      - near-cash-network
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:latest
    container_name: near-cash-redis
    hostname: near-cash-redis
    ports:
      - "6379:6379"
    networks:
      - near-cash-network
    restart: unless-stopped
    volumes:
      - redis_data:/data
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management
    container_name: near-cash-rabbitmq
    hostname: near-cash-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - near-cash-network
    restart: unless-stopped
    env_file:
      - .env

  database:
    image: postgis/postgis:15-3.3 #a postgres image with PostGIS support
    container_name: near-cash-database
    hostname: near-cash-database
    ports:
      - "5432:5432"
    networks:
      - near-cash-network
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: near-cash-celery-worker
    container_name: near-cash-celery-worker
    hostname: near-cash-celery-worker
    entrypoint: celery -A near_cash.celery worker --loglevel=info -E
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - database
    networks:
      - near-cash-network
    volumes:
      - .:/app
    restart: always

# scheduler for periodic tasks
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: near-cash-celery-beat
    container_name: near-cash-celery-beat
    hostname: near-cash-celery-beat
    entrypoint: celery -A near_cash.celery beat --loglevel=info --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - database
    networks:
      - near-cash-network
    volumes:
      - .:/app
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: near-cash-mailhog
    hostname: near-cash-mailhog
    ports:
      - "8026:8025"
      - "1026:1025"
    networks:
      - near-cash-network
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:

networks:
  near-cash-network:
