# Generated by Django 5.2.1 on 2025-06-21 22:15

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_address'),
    ]

    operations = [
        CreateExtension(name='postgis')
    ]
