# Generated by Django 5.2.1 on 2025-06-25 18:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business__location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326, verbose_name='Location Cordinates'),
        ),
    ]
