# Generated by Django 5.2.1 on 2025-07-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_business__location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='_location',
            new_name='geo_location',
        ),
        migrations.CreateModel(
            name='BusinessTransactionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('name', models.CharField(max_length=255, null=True)),
                ('cash_collection_mode', models.CharField(choices=[('MEET_UP', 'MEET_UP'), ('STORE_WALK_IN', 'STORE_WALK_IN'), ('MEET_UP_AND_STORE_WALK_IN', 'MEET_UP_AND_STORE_WALK_IN')], default='STORE_WALK_IN', max_length=255, null=True)),
                ('meet_up_charge', models.FloatField(default=0.0, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'verbose_name': 'business transaction policy',
                'verbose_name_plural': 'business transaction policies',
                'db_table': 'business_transaction_policy',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('business', models.ForeignKey(help_text='Business that created this category', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('txn_policy', models.ForeignKey(help_text='The transaction policy that applies to the clients in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesstransactionpolicy')),
            ],
            options={
                'verbose_name': 'categry for clients',
                'verbose_name_plural': 'category for clients',
                'db_table': 'business_client_category',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.business')),
                ('category', models.ForeignKey(help_text='category this client belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.businessclientcategory')),
                ('client', models.ForeignKey(help_text='The actual client added to this category', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category client',
                'verbose_name_plural': 'category clients',
                'db_table': 'category_client',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('business', 'client'), name='category_business_client_constraint')],
            },
        ),
    ]
