# Generated by Django 5.2.1 on 2025-07-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename__location_business_geo_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstransactionpolicy',
            name='description',
            field=models.TextField(default='General Policy', null=True),
        ),
    ]
