# Generated by Django 5.2.1 on 2025-07-12 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businesstransactionpolicy_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='categoryclient',
            name='category_business_client_constraint',
            constraint=models.UniqueConstraint(fields=('business', 'client'), name='category_business_client_constraint', violation_error_message='Client already belongs to a category in this business!'),
        ),
    ]
