# Generated by Django 5.2.1 on 2025-07-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categoryclient_category_business_client_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryclient',
            options={'ordering': ['-last_updated', '-date_created'], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
