# Generated by Django 5.2.1 on 2025-08-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categoryclient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-last_updated', '-date_created'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
    ]
