# Generated by Django 5.2.1 on 2025-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_business_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryclient',
            name='last_patronized',
            field=models.DateTimeField(null=True),
        ),
    ]
