# Generated by Django 5.2.1 on 2025-08-17 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoryclient_last_patronized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('last_patronized', models.DateTimeField(null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.business')),
                ('category', models.ForeignKey(help_text='category this client belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.businessclientcategory')),
                ('client', models.ForeignKey(help_text='The actual client added to this category', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business client',
                'verbose_name_plural': 'business clients',
                'db_table': 'business_client',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CategoryClient',
        ),
        migrations.AddConstraint(
            model_name='businessclient',
            constraint=models.UniqueConstraint(fields=('business', 'client'), name='category_business_client_constraint', violation_error_message='Client is already a patron of this business!'),
        ),
    ]
