# Generated by Django 5.2.1 on 2025-08-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_businessclient_delete_categoryclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='category',
            field=models.ForeignKey(help_text='category this client belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessclientcategory'),
        ),
    ]
