# Generated by Django 5.2.1 on 2025-10-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_businessclient_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
