# Generated by Django 5.2.1 on 2025-10-06 20:10

from django.db import migrations
from apps.core.management.commands.update_primary_vendor_primary_business import Command


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_business_is_primary'),
    ]

    operations = [
        migrations.RunPython(
            Command.handle, reverse_code=migrations.RunPython.noop
        )
    ]
