# Generated by Django 5.2.1 on 2025-10-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_currentlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentlocation',
            options={'ordering': ['-date_created'], 'verbose_name': 'current location', 'verbose_name_plural': 'current locations'},
        ),
        migrations.AlterModelTable(
            name='currentlocation',
            table='current_location',
        ),
    ]
