# Generated by Django 5.2.1 on 2026-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_currentlocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
