# Generated by Django 5.2.1 on 2026-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_business_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='available_liquidity',
            field=models.FloatField(help_text='POS Vendors are to set their available liquidity for the day\ngiving room for vendor ranking based on liquidity availabilty too.', null=True),
        ),
        migrations.AddField(
            model_name='businesstransactionpolicy',
            name='max_delivery_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='businesstransactionpolicy',
            name='max_delivery_distance',
            field=models.FloatField(help_text='maximum distance a vendor can delivery cash -- in km', null=True),
        ),
    ]
