# Generated by Django 5.2.1 on 2026-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_business_available_liquidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('FX', 'FX')], default='LOCAL', max_length=100),
        ),
    ]
