# Generated by Django 5.2.1 on 2026-08-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_business_business_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessclientcategory',
            options={'ordering': ['-last_updated', '-date_created'], 'verbose_name': 'category for clients', 'verbose_name_plural': 'categories for clients'},
        ),
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('currency_code', models.CharField(help_text='The ISO 4217 currency code', max_length=10, null=True)),
                ('available_liquidity', models.FloatField(default=0.0, help_text='The amount of this currency that the business has available for transactions')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_currencies', to='core.business')),
            ],
            options={
                'verbose_name': 'supported currency',
                'verbose_name_plural': 'supported currencies',
                'db_table': 'supported_currency',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('business', 'currency_code'), name='unique_business_currency', violation_error_message='This currency is already supported by this business!')],
            },
        ),
    ]
