# Generated by Django 5.2.1 on 2026-08-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_businessclientcategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportedCurrency',
        ),
    ]
