"""
Django settings for near_cash project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from corsheaders.defaults import default_headers, default_methods
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", cast=str, default='django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("ENVIRONMENT", "production").lower() in ("development", "dev", "local", "staging")

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS", cast=lambda v: [s.strip() for s in v.split(',')], default='*'
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'django.contrib.gis',  # for GIS support
    # third-party apps
    'rest_framework',
    'corsheaders',
    'graphene_django',
    'django_celery_beat',
    # project apps
    "apps.auths",
    "apps.core",
    "apps.wallet",
    "apps.notification",
    "apps.payment"
]

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = config(
    "ALLOWED_ORIGINS", cast=lambda v: [s.strip() for s in v.split(',')], default='http://localhost:3000'
)
CORS_ALLOWED_HEADERS = [
    *default_headers,
]
CORS_ALLOWED_METHODS = [
    *default_methods,
]

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=lambda v: [s.strip() for s in v.split(',')], default='http://localhost:3000')
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'near_cash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'near_cash.wsgi.application'
ASGI_APPLICATION = 'near_cash.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config("DB_NAME", cast=str, default='nearcash'),
        "USER": config("DB_USER", cast=str, default='postgres'),
        "PASSWORD": config("DB_PASSWORD", cast=str, default='password'),
        "HOST": config("DB_HOST", cast=str, default='localhost'),
        "PORT": config("DB_PORT", cast=int, default=5432),
    }
}

AUTH_USER_MODEL = "auths.User"
GRAPHENE = {
    "SCHEMA": "near_cash.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ]
}

AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ENVIRONMENT = config("ENVIRONMENT", cast=str, default='development')
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'nearcash': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

GOOGLE_REDIRECT_URI = config("GOOGLE_REDIRECT_URI", cast=str, default='http://localhost:8015/google/auth')
GOOGLE_API_KEY = config("GOOGLE_API_KEY", cast=str, default='your_google_api_key')

GEOAPIFY_BASE_URL = config("GEOAPIFY_BASE_URL", cast=str, default='https://api.geoapify.com/v1')
GEOAPIFY_API_KEY = config("GEOAPIFY_API_KEY", cast=str, default='your_geoapify_api_key')

FLUTTERWAVE_BASE_URL = config("FLUTTERWAVE_BASE_URL", cast=str, default="http://api.flutterwave.com")
FLUTTERWAVE_SECRET_KEY = config("FLUTTERWAVE_SECRET_KEY", cast=str, default=None)
DEFAULT_HTTP_TIMEOUT = config("DEFAULT_HTTP_TIMEOUT", cast=int, default=10000)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

CELERY_BROKER_URL = config("CELERY_BROKER_URL", cast=str, default='amqp://guest:guest@rabbitmq:5672//')
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", cast=str, default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULE = {
    "reminder-to-finalize-inprogress-txns": {
        "task": "update_inprogress_transactions",
        "schedule": crontab(
            day_of_week='*', hour='*/6', minute=0
        )
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", cast=str, default='localhost')
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=1025)
EMAIL_USE_TLS = (ENVIRONMENT in ['production', 'staging'])
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", cast=str, default="support@nearcash.com")
GENERAL_NOTIFICATION_GROUP_NAME = "nearcash_notifications"
OPPORTUNISTIC_VENDOR_GROUP = "transaction_opportunity"
