# Generated by Django 5.2.1 on 2025-10-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notificatio_content_743343_idx')],
            },
        ),
    ]
