# Generated by Django 5.2.1 on 2026-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notificatio_content_743343_idx_notificatio_content_3c688e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', null=True),
        ),
    ]
