# Generated by Django 5.2.1 on 2025-06-20 12:51

import django.db.models.deletion
import utils.helpers.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('business_id', models.CharField(help_text='Unique identifier for the business that owns the wallet', max_length=25)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='NGN', help_text='Currency of the wallet balance', max_length=15)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='FinancialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('range', models.CharField(help_text="The range of the asset, e.g., '1000-5000', '5000-10000', etc.", max_length=255)),
                ('charge_rate', models.FloatField(default=100.0, null=True, validators=[utils.helpers.validators.Validator.validate_number])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.business')),
            ],
            options={
                'verbose_name': 'Financial Asset',
                'verbose_name_plural': 'Financial Assets',
                'db_table': 'financial_asset',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('txn_ref', models.CharField(help_text='Unique reference for the transaction', max_length=100, unique=True)),
                ('charge', models.FloatField(help_text='amount charged for the txn')),
                ('currency', models.CharField(default='NGN', max_length=15)),
                ('collection_mode', models.CharField(choices=[('MEETUP', 'MEETUP'), ('OUTLET_WALK_IN', 'OUTLET_WALK_IN')], db_index=True, max_length=255, null=True)),
                ('txn_location', models.CharField(help_text='Location where the transaction is to be fulfilled', max_length=255)),
                ('discounted', models.BooleanField(default=False)),
                ('extra_charge', models.JSONField(blank=True, default=dict, help_text='Should contain amount and reason keys for the extra charge', null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('CANCELLED', 'CANCELLED'), ('FULFILLED', 'FULFILLED')], db_index=True, default='IN_PROGRESS', max_length=255)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(blank=True, help_text='help determines whether it is a product or service(system) txn', max_length=255, null=True)),
                ('wallet_id', models.CharField(blank=True, help_text='ID of the wallet used for the transaction', max_length=25, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.financialasset')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.business')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_transactions', related_query_name='client_transactions', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_transactions', related_query_name='vendor_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
            },
        ),
    ]
