# Generated by Django 5.2.1 on 2025-07-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='collection_mode',
            field=models.CharField(choices=[('MEET_UP', 'MEET_UP'), ('STORE_WALK_IN', 'STORE_WALK_IN')], db_index=True, max_length=255, null=True),
        ),
    ]
