# Generated by Django 5.2.1 on 2025-08-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_collection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialasset',
            name='currency_code',
            field=models.CharField(default='NGN', help_text='Currency code for the asset', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'INITIATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CANCELLED', 'CANCELLED'), ('FULFILLED', 'FULFILLED'), ('DECLINED', 'DECLINED')], db_index=True, default='INITIATED', max_length=255),
        ),
    ]
