# Generated by Django 5.2.1 on 2025-08-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_financialasset_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0, help_text='amount intended to be withdrawn'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charge',
            field=models.FloatField(default=0.0, help_text='amount charged for the txn'),
        ),
    ]
