# Generated by Django 5.2.1 on 2025-10-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_amount_alter_transaction_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-last_updated', '-date_created'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
