# Generated by Django 5.2.1 on 2026-03-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_business_available_liquidity_and_more'),
        ('wallet', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(help_text='the vendor business to which this opportunity was shared', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('transaction', models.ForeignKey(help_text='the transaction whose opportunity was shared to the given vendor', null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Opportunity',
                'verbose_name_plural': 'Transaction Opportunities',
                'db_table': 'transaction_opportunity',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('transaction', 'business'), name='one_opp_per_business')],
            },
        ),
    ]
