# Generated by Django 5.2.1 on 2026-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transactionopportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-last_updated', '-date_created'], 'verbose_name': 'wallet', 'verbose_name_plural': 'wallets'},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='business_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='BANK_TRANSFER', max_length=255),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the user that owns the wallet', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN_ACTIVE', 'IN_ACTIVE')], default='ACTIVE', max_length=255),
        ),
    ]
