# Generated by Django 5.2.1 on 2026-04-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallet_options_remove_wallet_business_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='collection_mode',
            field=models.CharField(choices=[('MEET_UP', 'MEET_UP'), ('STORE_WALK_IN', 'STORE_WALK_IN'), ('MEET_UP_AND_STORE_WALK_IN', 'MEET_UP_AND_STORE_WALK_IN')], db_index=True, max_length=255, null=True),
        ),
    ]
