# Generated by Django 5.2.1 on 2026-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_transaction_collection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('FX', 'FX'), ('LOCAL', 'LOCAL')], default='LOCAL', max_length=100),
        ),
    ]
