# Generated by Django 5.2.1 on 2026-09-20 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_supportedcurrency'),
        ('wallet', '0011_supportedcurrency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['txn_ref', 'status', 'id', 'date_created', 'last_updated'], name='txn_ref_status_id_date_idx'),
        ),
    ]
