# Generated by Django 5.2.1 on 2026-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_transaction_txn_ref_status_id_date_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_mode',
            field=models.CharField(choices=[('CARD', 'CARD'), ('BANK_TRANSFER', 'BANK_TRANSFER'), ('CASH', 'CASH')], default='BANK_TRANSFER', max_length=255),
        ),
    ]
