# Generated by Django 5.2.1 on 2026-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_transaction_transfer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
