# Generated by Django 5.2.1 on 2025-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_channel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
