# Generated by Django 5.2.1 on 2025-06-07 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('source', models.CharField(blank=True, choices=[('GOOGLE', 'GOOGLE'), ('FACEBOOK', 'FACEBOOK')], max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SocialToken',
                'verbose_name_plural': 'SocialTokens',
                'db_table': 'social_token',
            },
        ),
    ]
