# Generated by Django 5.2.1 on 2025-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_socialtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
