# Generated by Django 5.2.1 on 2025-11-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_updated', '-date_created'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
