# Generated by Django 5.2.1 on 2026-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bvn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remittance_account_number',
            field=models.CharField(blank=True, help_text='Account number into which money is to be paid into, by the system-- mostly needed for vendors remittance', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remittance_bank_code',
            field=models.CharField(blank=True, help_text='CBN code for the bank that issued the account number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remittance_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thirdparty_payment_customer_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
