# Generated by Django 5.2.1 on 2026-03-23 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlatformToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('source', models.CharField(blank=True, choices=[('FLUTTERWAVE', 'FLUTTERWAVE'), ('PAYSTACK', 'PAYSTACK'), ('ANCHOR', 'ANCHOR')], default='FLUTTERWAVE', max_length=255, null=True)),
                ('expires_in', models.DurationField(blank=True, default=datetime.timedelta(seconds=600), null=True)),
            ],
            options={
                'verbose_name': 'payment_platform_token',
                'verbose_name_plural': 'payment_platform_tokens',
                'db_table': 'payment_platform_token',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
            },
        ),
    ]
