# Generated by Django 5.2.1 on 2026-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplatformtoken',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
