# Generated by Django 5.2.1 on 2026-03-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentplatformtoken_token'),
        ('wallet', '0007_alter_wallet_options_remove_wallet_business_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('source', models.CharField(blank=True, choices=[('FLUTTERWAVE', 'FLUTTERWAVE'), ('PAYSTACK', 'PAYSTACK')], null=True)),
                ('event', models.JSONField(default=dict, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction')),
            ],
            options={
                'verbose_name': 'payment_platform_event',
                'verbose_name_plural': 'payment_platform_events',
                'db_table': 'payment_platform_event',
                'ordering': ['-last_updated', '-date_created'],
                'abstract': False,
            },
        ),
    ]
