# Generated by Django 5.2.1 on 2026-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentplatformevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplatformevent',
            name='event_type',
            field=models.CharField(blank=True, help_text='Name of the event from the platform that sends it.', max_length=100, null=True),
        ),
    ]
