MEET_UP = "MEET_UP"
OUTLET_WALK_IN = "OUTLET_WALK_IN"
STORE_WALK_IN = "STORE_WALK_IN"
IN_PROGRESS = "IN_PROGRESS"
CANCELLED = "CANCELLED"
FULFILLED = "FULFILLED"
DECLINED = "DECLINED"
INITIATED = "INITIATED"
CARD = "CARD"
BANK_TRANSFER = "BANK_TRANSFER"

COLLECTION_MODES = [
    (MEET_UP, MEET_UP),
    (STORE_WALK_IN, STORE_WALK_IN),
]

TXN_STATUSES = [
    (INITIATED, INITIATED),
    (IN_PROGRESS, IN_PROGRESS),
    (CANCELLED, CANCELLED),
    (FULFILLED, FULFILLED),
    (DECLINED, DECLINED),
]


TRANSFER_MODES = [
    (CARD, CARD),
    (BANK_TRANSFER, BANK_TRANSFER)
]
