from django.conf import settings

MEET_UP = "MEET_UP"
OUTLET_WALK_IN = "OUTLET_WALK_IN"
STORE_WALK_IN = "STORE_WALK_IN"
MEET_UP_AND_STORE_WALK_IN = "MEET_UP_AND_STORE_WALK_IN"
IN_PROGRESS = "IN_PROGRESS"
CANCELLED = "CANCELLED"
FULFILLED = "FULFILLED"
DECLINED = "DECLINED"
INITIATED = "INITIATED"
CARD = "CARD"
BANK_TRANSFER = "BANK_TRANSFER"
FX = "FX"
LOCAL = "LOCAL"
CASH = "CASH"

COLLECTION_MODES = [
    (MEET_UP, MEET_UP),
    (STORE_WALK_IN, STORE_WALK_IN),
    (MEET_UP_AND_STORE_WALK_IN, MEET_UP_AND_STORE_WALK_IN)
]

TXN_STATUSES = [
    (INITIATED, INITIATED),
    (IN_PROGRESS, IN_PROGRESS),
    (CANCELLED, CANCELLED),
    (FULFILLED, FULFILLED),
    (DECLINED, DECLINED),
]


TRANSFER_MODES = [
    (CARD, CARD),
    (BANK_TRANSFER, BANK_TRANSFER)
]


TRANSACTION_TYPES = [
    (FX, FX),
    (LOCAL, LOCAL)
]


EXCHANGE_RATE_SERVICES = {
    "TWELVEDATA": {
        "url": "https://api.twelvedata.com",
        "api_key": settings.TWELVEDATA_API_KEY,
        "default_headers": {
            "Authorization": f"apikey {settings.TWELVEDATA_API_KEY}",
            "Content-Type": "application/json"
        }
    }
}
