MEETUP = "MEETUP"
OUTLET_WALK_IN = "OUTLET_WALK_IN"
IN_PROGRESS = "IN_PROGRESS"
CANCELLED = "CANCELLED"
FULFILLED = "FULFILLED"

COLLECTION_MODES = [
    (MEETUP, MEETUP),
    (OUTLET_WALK_IN, OUTLET_WALK_IN),
]

TXN_STATUSES = [
    (IN_PROGRESS, IN_PROGRESS),
    (CANCELLED, CANCELLED),
    (FULFILLED, FULFILLED),
]